ReviewAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReviewAdmin.Data;
using ReviewAdmin.Models;

namespace ReviewAdmin.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Terminals
        public async Task<IActionResult> Index()
        {
            return View(await _context.Terminal.ToListAsync());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ReviewAdmin/Controllers/TerminalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReviewAdmin.Data;
using ReviewAdmin.Models;

namespace ReviewAdmin.Controllers
{
    [Authorize]
    public class TerminalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TerminalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Terminals
        public async Task<IActionResult> Index()
        {
            return View(await _context.Terminal.ToListAsync());
        }

        // GET: Terminals/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terminal = await _context.Terminal
                .FirstOrDefaultAsync(m => m.Name == id);
            if (terminal == null)
            {
                return NotFound();
            }

            return View(terminal);
        }

        // GET: Terminals/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terminal = await _context.Terminal
                .Include(t =>t.Answers)
                .FirstOrDefaultAsync(t => t.Name == id);
            //var terminals = await _context.Terminal.FindAsync(id);
            if (terminal == null)
            {
                return NotFound();
            }
            return View(terminal);
        }

        // POST: Terminals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Description,LastAlive")] Terminal terminal)
        {
            if (id != terminal.Name)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(terminal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TerminalExists(terminal.Name))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "");
                //return RedirectToAction(nameof(Index));
            }
            return View(terminal);
        }

        // GET: Terminals/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terminal = await _context.Terminal
                .FirstOrDefaultAsync(m => m.Name == id);
            if (terminal == null)
            {
                return NotFound();
            }

            return View(terminal);
        }

        // POST: Terminals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var terminal = await _context.Terminal.FindAsync(id);
            _context.Terminal.Remove(terminal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), "Home");
        }

        private bool TerminalExists(string id)
        {
            return _context.Terminal.Any(e => e.Name == id);
        }
    }
}

ReviewAdmin/Views/Home/Index.cshtml
@model IEnumerable<ReviewAdmin.Models.Terminal>

@{
    ViewData["Title"] = "Terminálok";
}

<div class="container ml-0">
    <div class="row">
        <div class="col">
            <h2>Terminálok</h2>
        </div>
    </div>

    @{
        @:<div class="row mt-5 w-75">
            int i = 0;
            foreach (var terminal in Model)
            {
                string color = (DateTime.Now - terminal.LastAlive).TotalMilliseconds < 3600000 ? "green" : "black";
                <div class="col-4">
                    <a asp-controller="Terminals" asp-action="Edit" asp-route-id="@terminal.Name">
                        <span class="large-icon" data-feather="monitor" color="@color"></span><br />
                    </a>
                    <b>@terminal.Name</b><br />
                    Legutóbbi bejelentkezés:<br />
                    @terminal.LastAlive
                </div>
                if (i % 3 == 2)
                {
                @:</div><div class="row mt-5">
                }
            }
        @:</div>
    }

</div>

@section scripts {
    <script>
        $(document).ready(function () {
            $('.nav-link').removeClass('active');
            $('#home').addClass('active');
        });

    </script>
}